### ISSUE TITLE
Tests can't run if BOOKS_API_KEY is unset

### ISSUE THREAD

**Issue by tiger-jmw** [Jackevansevo/DjangoLibrary#2]
```
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/travis/build/tigercomputing/DjangoLibrary/books/models.py", line 13, in <module>
    from .isbn import meta
  File "/home/travis/build/tigercomputing/DjangoLibrary/books/isbn.py", line 13, in <module>
    api_key = environ['BOOKS_API_KEY']
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/os.py", line 725, in __getitem__
    raise KeyError(key) from None
KeyError: 'BOOKS_API_KEY'
```

**Comment by tiger-jmw** [comment]
A default or test key probably isn't fruitful; maybe tests relying on the key should be skipped if it isn't present?
